name: conda-on-air  # conda env name of your project
path: conda/on-air  # path for the patches
version: "1.0.0"  # version of the conda-on-air specs
packages:
  pre-commit:
    url: https://github.com/conda-forge/pre-commit-feedstock
    rev: 0593e8a384918569be52ae290f9b9a6bb32584ea
    version: "3.3.2"
  ruff:
    url: https://github.com/conda-forge/ruff-feedstock
    rev: 0ae59491cee124fc91bdc4092f4dcaeca3de531c
    version: "0.0.269"
