name: conda-on-air
channels:
  - nodefaults
  - conda-forge
dependencies:
  - conda-build
  - git
  - nodejs  # used by semantic-release
  - python <3.11
  - poetry
  - urllib3 <2  # due an issue with poetry
